import { useEffect } from 'react';
import { Icon } from '../../show/ui.jsx';
import { call, g, getStore } from '../../show/bridge.js';

const Spacer=()=> <div className="spacer"/>;
const Field=({label,id,value='',placeholder,type='text',children,...rest})=><div className="field"><label>{label}</label>{children||<input id={id} type={type} className="input" defaultValue={value||''} placeholder={placeholder} {...rest}/>}</div>;

export function SettingsHomeAirportSheet({value}){
  const current=value||getStore()?.settings?.homeAirport||'AMS';
  useEffect(()=>{const t=setTimeout(()=>document.getElementById('ha-code')?.focus(),300);return()=>clearTimeout(t)},[]);
  return <><Field label="Airport code (IATA)" id="ha-code" value={current} placeholder="AMS" maxLength={4} style={{textTransform:'uppercase'}}/><div className="hint" style={{textAlign:'left',padding:'2px 2px 12px'}}>A tour ends whenever a flight brings you back here. Change this and tours regroup automatically.</div><button className="btn" onClick={()=>{const s=getStore()?.settings;if(!s)return;const v=document.getElementById('ha-code')?.value.trim()||'AMS';s.homeAirport=v.toUpperCase();if(s.baseCurrencyAuto!==false)s.baseCurrency=call('homeCurrency');call('persist','settings');call('closeSheet');call('renderView');call('toast','Home airport set','check')}}>Save</button><Spacer/></>;
}
export function SettingsProfileNameSheet({value}){
  const s=getStore()?.settings||{}, current=value??(s.artistName==='You'?'':s.artistName||'');
  useEffect(()=>{const t=setTimeout(()=>document.getElementById('pf-name')?.focus(),300);return()=>clearTimeout(t)},[]);
  return <><Field label="Name / act" id="pf-name" value={current} placeholder="Your DJ / act name"/><button className="btn" onClick={()=>{s.artistName=document.getElementById('pf-name')?.value.trim()||'You';call('persist','settings');call('closeSheet');call('renderView');call('toast','Saved','check')}}>Save</button><Spacer/></>;
}
export function SettingsCurrencySheet({settings}){
  const s=settings||getStore()?.settings||{}, currencies=Object.keys(s.fx||{});
  return <><Field label="Base currency"><select id="set-base" className="input" defaultValue={s.baseCurrency}>{currencies.map(c=><option value={c} key={c}>{c} {(g('CURSYM')||{})[c]?`(${g('CURSYM')[c]})`:''}</option>)}</select><div className="hint" style={{textAlign:'left',padding:'6px 2px'}}>All earnings roll up into this currency.</div></Field><div className="field"><label>Exchange rates (value of 1 unit in {s.baseCurrency})</label><div id="set-rates">{currencies.filter(c=>c!==s.baseCurrency).map(c=><div key={c} style={{display:'flex',alignItems:'center',gap:10,marginBottom:8}}><span style={{width:52,fontWeight:700,color:'var(--text-2)'}}>{c}</span><input className="input" data-cur={c} type="number" step="0.0001" inputMode="decimal" defaultValue={s.fx[c]} style={{flex:1,padding:'9px 12px'}}/></div>)}</div></div><button className="btn" id="set-save" onClick={()=>call('saveCurrency')}>Save rates</button><Spacer/></>;
}
export function SettingsPackingSheet({items}){
  const list=items||getStore()?.settings?.packingTemplate||[];
  return <><div className="field"><label>One item per line</label><textarea id="set-pack" className="textarea" style={{minHeight:200}} defaultValue={list.join('\n')}/><div className="hint" style={{textAlign:'left',padding:'6px 2px'}}>Added to every new trip.</div></div><button className="btn" onClick={()=>{const s=getStore()?.settings;if(!s)return;s.packingTemplate=(document.getElementById('set-pack')?.value||'').split('\n').map(x=>x.trim()).filter(Boolean);call('persist','settings');call('closeSheet');call('renderView');call('toast','Saved','check')}}>Save list</button><Spacer/></>;
}

export function AuthInviteSheet(){
  return <><Field label="Email" id="inv-email" type="email" placeholder="crew@example.com" autoComplete="email"/><Field label="Role"><div className="seg" id="inv-role"><button data-v="crew" className="on" onClick={e=>call('segPick',e.currentTarget)}>Crew</button><button data-v="manager" onClick={e=>call('segPick',e.currentTarget)}>Manager</button></div></Field><div className="hint" style={{textAlign:'left',padding:'2px 2px 10px',lineHeight:1.5}}>Crew can update day-of details. Managers can edit everything.</div><button className="btn" id="inv-make" onClick={()=>call('doCreateInvite')}>Create invite link</button><div id="inv-out" style={{marginTop:12}}/><Spacer/></>;
}
export function AuthAccountSheet({mode,email,statusLabel,message,singleAccount=false,allowedEmail=''}) {
  if(mode==='unconfigured'||mode==='disabled') return <><div className="hint" style={{textAlign:'left',padding:'2px 2px 16px',lineHeight:1.5}}>{message|| (mode==='unconfigured'?'Cloud sync is not configured. Add your Supabase credentials to enable it.':'Cloud sync is not enabled yet. Your tour data stays on this device.')}</div><Spacer/></>;
  if(mode==='dev') return <><div className="card" style={{padding:15,marginBottom:6,textAlign:'center'}}><div style={{fontSize:11.5,color:'var(--text-3)',fontWeight:700,textTransform:'uppercase',letterSpacing:'.08em'}}>Dev mode</div><div style={{fontSize:16,fontWeight:700,marginTop:4}}>No sign-in</div><div id="sync-status" style={{fontSize:13,color:'var(--text-2)',marginTop:4}}>{statusLabel||call('syncStatusLabel')}</div></div><div className="hint" style={{textAlign:'left',padding:'8px 2px 14px',lineHeight:1.5}}>All tour data syncs to the shared dev organisation.</div><button className="btn secondary" onClick={()=>call('syncPullNow')}><Icon name="reminder" size={16}/> Refresh now</button><Spacer/></>;
  if(mode==='signin') return <><div className="hint" style={{textAlign:'left',padding:'2px 2px 14px',lineHeight:1.5}}>{message||'Sign in to load and save tour data.'}</div><Field label="Email" id="auth-email" type="email" value={allowedEmail} placeholder="you@example.com" autoComplete="email" readOnly={!!allowedEmail}/><p id="auth-msg" className="auth-msg"/><button className="btn" id="auth-send" onClick={()=>call('sendMagicLink')}>Send magic link</button><Spacer/></>;
  return <><div className="card" style={{padding:15,marginBottom:6,textAlign:'center'}}><div style={{fontSize:11.5,color:'var(--text-3)',fontWeight:700,textTransform:'uppercase',letterSpacing:'.08em'}}>Signed in as</div><div style={{fontSize:16,fontWeight:700,marginTop:4}}>{email||'Not signed in'}</div><div id="sync-status" style={{fontSize:13,color:'var(--text-2)',marginTop:4}}>{statusLabel||call('syncStatusLabel')}</div></div><div className="hint" style={{textAlign:'left',padding:'8px 2px 14px',lineHeight:1.5}}>Your tour data syncs across signed-in devices.</div>{!singleAccount?<button className="btn secondary" onClick={()=>call('sheetInviteCrew')}><Icon name="users" size={16}/> Invite crew</button>:null}<button className="btn secondary" style={{marginTop:10}} onClick={()=>call('syncPullNow')}><Icon name="reminder" size={16}/> Refresh now</button><button className="btn secondary" style={{marginTop:10}} onClick={()=>call('exportData')}><Icon name="file" size={16}/> Export my data</button><button className="btn danger" style={{marginTop:10}} onClick={()=>call('signOut')}><Icon name="x" size={16}/> Sign out</button><button className="btn danger" style={{marginTop:10}} onClick={()=>call('confirmDeleteCloudData')}><Icon name="trash" size={16}/> Delete all cloud data</button><Spacer/></>;
}
