# Operate — Supabase dev setup helper
# Run from repo root: .\scripts\setup-dev.ps1

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$configPath = Join-Path $root "js\config.js"

Write-Host ""
Write-Host "=== Operate Supabase Dev Setup ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "If you haven't created a project yet, follow:" -ForegroundColor Yellow
Write-Host "  supabase/SETUP_WALKTHROUGH.md" -ForegroundColor White
Write-Host ""
Write-Host "Opening Supabase dashboard..." -ForegroundColor Gray
Start-Process "https://supabase.com/dashboard/projects"

$url = Read-Host "Paste Project URL (https://xxxxx.supabase.co)"
$key = Read-Host "Paste anon public key (eyJ...)"

$url = $url.Trim()
$key = $key.Trim()

if ($url -notmatch '^https://.+\.supabase\.co/?$') {
  Write-Host "Invalid URL format." -ForegroundColor Red
  exit 1
}
if ($key.Length -lt 20) {
  Write-Host "Anon key looks too short." -ForegroundColor Red
  exit 1
}

$content = @"
// Generated by scripts/setup-dev.ps1 — gitignored
window.OPERATE_CONFIG = {
  SUPABASE_URL: '$($url.TrimEnd('/'))',
  SUPABASE_ANON_KEY: '$key',
};
"@

Set-Content -Path $configPath -Value $content -Encoding UTF8
Write-Host ""
Write-Host "Wrote js/config.js" -ForegroundColor Green

# Verify REST endpoint responds
try {
  $headers = @{ apikey = $key; Authorization = "Bearer $key" }
  $health = Invoke-RestMethod -Uri "$($url.TrimEnd('/'))/rest/v1/" -Headers $headers -Method Get -TimeoutSec 15
  Write-Host "Supabase REST API: OK" -ForegroundColor Green
} catch {
  Write-Host "Warning: could not reach REST API ($($_.Exception.Message))" -ForegroundColor Yellow
  Write-Host "Check URL/key and try again." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Run combined_dev_setup.sql in SQL Editor (if not done)" -ForegroundColor White
Write-Host "  2. Configure magic link auth (see SETUP_WALKTHROUGH.md Step C)" -ForegroundColor White
Write-Host "  3. npx serve . -l 3000" -ForegroundColor White
Write-Host "  4. Open http://localhost:3000 and sign in" -ForegroundColor White
Write-Host ""
